#Status plugin made by Niekert. SO to Thunder33345 for helping with small things.
webhook_url: "" #Your webhook url.
chat_url: "" #Webhook url for the /discord command. Set to 0 to use default.
username: "" #The username the plugin uses.
chat_username: "" #The username of the plugin when someone says something. Set to 0 to use default.

#Messages
start_message: "" #Message when server starts. Set to 0 to disable.
shutdown_message: "" #Message when server stops. Set to 0 to disable.
join_message: "" #Message when player joins. {player} can be used. Set to 0 to disable.
quit_message: "" #Message when player leaves. {player} can be used. Set to 0 to disable.
death_message: "" #Message when player get killed. {player} can be used. Set to 0 to disable.
chat_format: "[{player}] {message}" #Format the plugin uses when someone says something. {player} and {message} can be used.

#Options
command: "1" #Command option. Set to 0 to disable.
chat_prefix: "!" #Prefix for chat. Set to 0 to disable.
chat: "0" #Send everything to Discord. EXTREMELY NOT RECOMMENDED! Set to 0 to disable, set to 1 to enable.
debug: "0" #Debug errors. Set to 0 to disable, set to 1 to enable.